export default {
id: "tt13818410",
title: "The Queen's Gambit",
originalTitle: "",
fullTitle: "Creating the Queen's Gambit (2021)",
type: "Movie",
year: "2021",
image: "https://imdb-api.com/images/original/MV5BMWZjMDcxNTQtZTM2Mi00YzU5LWJlOWEtNTdhMzk5Y2EyNjMxXkEyXkFqcGdeQXVyMTA3OTA3NTYz._V1_Ratio0.7015_AL_.jpg",
releaseDate: "2021-01-10",
runtimeMins: "14",
runtimeStr: "14mins",
plot: "Nine year-old orphan Beth Harmon is quiet, sullen, and by all appearances unremarkable. That is, until she plays her first game of chess. Her senses grow sharper, her thinking clearer, and for the first time in her life she feels herself fully in control. By the age of sixteen, she's competing for the U.S. Open championship. But as Beth hones her skills on the professional circuit, the stakes get higher, her isolation grows more frightening, and the thought of escape becomes all the more tempting. Based on the book by Walter Tevis.",
plotLocal: "",
plotLocalIsRtl: false,
awards: "Top Rated TV #148 | Won 2 Golden Globes. Another 12 wins & 19 nominations.",
directors: "",
directorList: [ ],
writers: "",
writerList: [ ],
stars: "Gabriele Binder, Thomas Brodie-Sangster, Bill Camp, Scott Frank",
starList: [
{
id: "nm0082778",
name: "Gabriele Binder",
},
{
id: "nm1032473",
name: "Thomas Brodie-Sangster",
},
{
id: "nm0131966",
name: "Bill Camp",
},
{
id: "nm0291082",
name: "Scott Frank",
},
],
actorList: [
{
id: "nm0082778",
image: "https://imdb-api.com/images/original/MV5BZjAxNGJkMGYtY2U0OC00YWVjLTlhZWEtNGI5MGUxNDA1NzYyXkEyXkFqcGdeQXVyMTk0MzgwMDY@._V1_Ratio0.7273_AL_.jpg",
name: "Gabriele Binder",
asCharacter: "Self / Costume Designer The Queens Gambit",
},
{
id: "nm1032473",
image: "https://imdb-api.com/images/original/MV5BMTM4OTUyMzY0OV5BMl5BanBnXkFtZTcwMTEyMTUwOA@@._V1_Ratio0.7273_AL_.jpg",
name: "Thomas Brodie-Sangster",
asCharacter: "Self / Benny Watts",
},
{
id: "nm0131966",
image: "https://imdb-api.com/images/original/MV5BMTU0MTI1NTMxN15BMl5BanBnXkFtZTgwNTkxMjI2NDM@._V1_Ratio0.8182_AL_.jpg",
name: "Bill Camp",
asCharacter: "Self / Mr. Shaibel (archive footage)",
},
{
id: "nm0291082",
image: "https://imdb-api.com/images/original/MV5BMTY0MTc5OTQwMV5BMl5BanBnXkFtZTYwODgxMDY0._V1_Ratio0.7273_AL_.jpg",
name: "Scott Frank",
asCharacter: "Self / Creator / Director",
},
{
id: "nm0359914",
image: "https://imdb-api.com/images/original/nopicture.jpg",
name: "Uli Hanisch",
asCharacter: "Self / Production Designer The Queens Gambit",
},
{
id: "nm1716636",
image: "https://imdb-api.com/images/original/MV5BMTgwOTcxMjY5OF5BMl5BanBnXkFtZTcwODA2MTIzOA@@._V1_Ratio0.7273_AL_.jpg",
name: "Marielle Heller",
asCharacter: "Self / Alma Wheatley (archive footage)",
},
{
id: "nm9548332",
image: "https://imdb-api.com/images/original/MV5BZDhmYTZiZTAtOGY3MS00OTBhLTgwZWMtYWVjNGM5YWI2MGNlXkEyXkFqcGdeQXVyMTI0ODI4NTEx._V1_Ratio0.7273_AL_.jpg",
name: "Isla Johnston",
asCharacter: "Self / Young Beth (archive footage)",
},
{
id: "nm11381138",
image: "https://imdb-api.com/images/original/MV5BOWJlNTUxNDktZDU5Zi00NjljLWIwNzMtNjY5MGNiOWQ5Mjg5XkEyXkFqcGdeQXVyMTE0MTA4OTY3._V1_Ratio0.7273_AL_.jpg",
name: "Annabeth Kelly",
asCharacter: "Self / Beth 5 Years (archive footage)",
},
{
id: "nm3082709",
image: "https://imdb-api.com/images/original/nopicture.jpg",
name: "Alexander Lambriev",
asCharacter: "Self / Property Master The Queens Gambit",
},
{
id: "nm0577152",
image: "https://imdb-api.com/images/original/nopicture.jpg",
name: "Steven Meizler",
asCharacter: "Self / Cinematographer The Queens Gambit",
},
{
id: "nm0659283",
image: "https://imdb-api.com/images/original/nopicture.jpg",
name: "Bruce Pandolfini",
asCharacter: "Self / Chess Advisor",
},
{
id: "nm0662173",
image: "https://imdb-api.com/images/original/nopicture.jpg",
name: "Daniel Parker",
asCharacter: "Self / Hair & Makeup Artist The Queens Gambit",
},
{
id: "nm1234252",
image: "https://imdb-api.com/images/original/nopicture.jpg",
name: "Sabine Schaaf",
asCharacter: "Self / Set Decorator The Queens Gambit",
},
{
id: "nm0778819",
image: "https://imdb-api.com/images/original/MV5BMzk5ZGEyNWUtNzhjZC00MGVhLTkwOTgtZWM5NjM5NGMwOTQyXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.0000_AL_.jpg",
name: "Allan Scott",
asCharacter: "Self / Co-Creator",
},
{
id: "nm5896355",
image: "https://imdb-api.com/images/original/MV5BYWUxMzhlM2QtNDM5MS00OThlLTlhZDEtMDhlNTliZDIzZGQ1XkEyXkFqcGdeQXVyNzcyNzc0NzE@._V1_Ratio0.7727_AL_.jpg",
name: "Anya Taylor-Joy",
asCharacter: "Self / Beth Harmon",
},
{
id: "nm4757927",
image: "https://imdb-api.com/images/original/MV5BNzQ0NmZiNDUtODMzOS00Y2U1LTlkNWMtMzNiZmRhY2JjY2E1XkEyXkFqcGdeQXVyMzIwMjcyNDM@._V1_Ratio0.7273_AL_.jpg",
name: "Eloise Webb",
asCharacter: "Self / Annette Packer (archive footage)",
},
],
fullCast: null,
genres: "Documentary, Short",
genreList: [
{
key: "Documentary",
value: "Documentary",
},
{
key: "Short",
value: "Short",
},
],
companies: "",
companyList: [ ],
countries: "USA",
countryList: [
{
key: "USA",
value: "USA",
}
],
languages: "English",
languageList: [
{
key: "English",
value: "English",
}
],
contentRating: "",
imDbRating: "6.9",
imDbRatingVotes: "346",
metacriticRating: "",
ratings: null,
wikipedia: null,
posters: {
imDbId: "tt13818410",
title: "Creating the Queen's Gambit",
fullTitle: "Creating the Queen's Gambit (2021)",
type: "Movie",
year: "2021",
posters: [
{
id: "gKxPyeItCrOscP8On4y5sG3WY9A.jpg",
link: "https://imdb-api.com/posters/original/gKxPyeItCrOscP8On4y5sG3WY9A.jpg",
aspectRatio: 0.6666666666666666,
language: "en",
width: 2000,
height: 3000,
},
{
id: "4PrWnaWdcZoTC9Xxyr0UZYS3ppw.jpg",
link: "https://imdb-api.com/posters/original/4PrWnaWdcZoTC9Xxyr0UZYS3ppw.jpg",
aspectRatio: 0.6666666666666666,
language: "en",
width: 500,
height: 750,
},
{
id: "6XFnup9IOl2DBLkFph5CjLfHgCu.jpg",
link: "https://imdb-api.com/posters/original/6XFnup9IOl2DBLkFph5CjLfHgCu.jpg",
aspectRatio: 0.6666666666666666,
language: "en",
width: 1066,
height: 1599,
},
],
backdrops: [
{
id: "4aTonMQCSEgu5PV3n3xRaNMZmG1.jpg",
link: "https://imdb-api.com/posters/original/4aTonMQCSEgu5PV3n3xRaNMZmG1.jpg",
aspectRatio: 1.7777777777777777,
language: "en",
width: 1280,
height: 720,
}
],
errorMessage: "",
},
images: null,
trailer: null,
boxOffice: {
budget: "",
openingWeekendUSA: "",
grossUSA: "",
cumulativeWorldwideGross: "",
},
tagline: "",
keywords: "making of,about filmmaking",
keywordList: [
"making of",
"about filmmaking",
],
similars: [
{
id: "tt0944947",
title: "Game of Thrones",
fullTitle: "Game of Thrones (2011–2019)",
year: "2011–2019",
image: "https://imdb-api.com/images/original/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_Ratio0.7368_AL_.jpg",
plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
directors: "",
stars: "Emilia Clarke, Peter Dinklage, Kit Harington",
genres: "Action, Adventure, Drama",
imDbRating: "9.3",
},
{
id: "tt2442560",
title: "Peaky Blinders",
fullTitle: "Peaky Blinders (TV Series 2013)",
year: "TV Series 2013",
image: "https://imdb-api.com/images/original/MV5BMTkzNjEzMDEzMF5BMl5BanBnXkFtZTgwMDI0MjE4MjE@._V1_Ratio0.6737_AL_.jpg",
plot: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
directors: "",
stars: "Cillian Murphy, Paul Anderson, Helen McCrory",
genres: "Crime, Drama",
imDbRating: "8.8",
},
{
id: "tt0903747",
title: "Breaking Bad",
fullTitle: "Breaking Bad (2008–2013)",
year: "2008–2013",
image: "https://imdb-api.com/images/original/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_Ratio0.7158_AL_.jpg",
plot: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
directors: "",
stars: "Bryan Cranston, Aaron Paul, Anna Gunn",
genres: "Crime, Drama, Thriller",
imDbRating: "9.5",
},
{
id: "tt4574334",
title: "Stranger Things",
fullTitle: "Stranger Things (TV Series 2016)",
year: "TV Series 2016",
image: "https://imdb-api.com/images/original/MV5BMjEzMDAxOTUyMV5BMl5BanBnXkFtZTgwNzAxMzYzOTE@._V1_Ratio0.6737_AL_.jpg",
plot: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
directors: "",
stars: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
genres: "Drama, Fantasy, Horror",
imDbRating: "8.7",
},
{
id: "tt4786824",
title: "The Crown",
fullTitle: "The Crown (TV Series 2016)",
year: "TV Series 2016",
image: "https://imdb-api.com/images/original/MV5BZmY0MzBlNjctNTRmNy00Njk3LWFjMzctMWQwZDAwMGJmY2MyXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_Ratio0.6737_AL_.jpg",
plot: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
directors: "",
stars: "Claire Foy, Olivia Colman, Imelda Staunton",
genres: "Biography, Drama, History",
imDbRating: "8.7",
},
{
id: "tt8740790",
title: "Bridgerton",
fullTitle: "Bridgerton (TV Series 2020)",
year: "TV Series 2020",
image: "https://imdb-api.com/images/original/MV5BYjIxMzZhMTMtNDQ1Mi00OTMwLTk2M2ItYzA0YmNjNDFlOTdhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6737_AL_.jpg",
plot: "Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.",
directors: "",
stars: "Phoebe Dynevor, Regé-Jean Page, Nicola Coughlan",
genres: "Drama, Romance",
imDbRating: "7.3",
},
{
id: "tt7366338",
title: "Chernobyl",
fullTitle: "Chernobyl (2019)",
year: "2019",
image: "https://imdb-api.com/images/original/MV5BZGQ2YmMxZmEtYjI5OS00NzlkLTlkNTEtYWMyMzkyMzc2MDU5XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_Ratio0.6737_AL_.jpg",
plot: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
directors: "",
stars: "Jessie Buckley, Jared Harris, Stellan Skarsgård",
genres: "Drama, History, Thriller",
imDbRating: "9.4",
},
{
id: "tt2531336",
title: "Lupin",
fullTitle: "Lupin (TV Series 2021)",
year: "TV Series 2021",
image: "https://imdb-api.com/images/original/MV5BNzRlNGUzMmEtYTg0Ni00N2U2LTg4YWEtNDdlNmMwYjBlZDQ0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6737_AL_.jpg",
plot: "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.",
directors: "",
stars: "Omar Sy, Vincent Londez, Ludivine Sagnier",
genres: "Action, Crime, Drama",
imDbRating: "7.6",
},
{
id: "tt8111088",
title: "The Mandalorian",
fullTitle: "The Mandalorian (TV Series 2019)",
year: "TV Series 2019",
image: "https://imdb-api.com/images/original/MV5BZDhlMzY0ZGItZTcyNS00ZTAxLWIyMmYtZGQ2ODg5OWZiYmJkXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_Ratio0.6737_AL_.jpg",
plot: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
directors: "",
stars: "Pedro Pascal, Gina Carano, Giancarlo Esposito",
genres: "Action, Adventure, Sci-Fi",
imDbRating: "8.8",
},
{
id: "tt7286456",
title: "Joker",
fullTitle: "Joker (2019)",
year: "2019",
image: "https://imdb-api.com/images/original/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6737_AL_.jpg",
plot: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
directors: "Todd Phillips",
stars: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
genres: "Crime, Drama, Thriller",
imDbRating: "8.4",
},
{
id: "tt4520364",
title: "Morgan",
fullTitle: "Morgan (2016)",
year: "2016",
image: "https://imdb-api.com/images/original/MV5BMjA1MjYyNDkxN15BMl5BanBnXkFtZTgwMTgxODAwOTE@._V1_Ratio0.6737_AL_.jpg",
plot: "A corporate risk-management consultant must decide whether or not to terminate an artificially created humanoid being.",
directors: "Luke Scott",
stars: "Kate Mara, Anya Taylor-Joy, Rose Leslie",
genres: "Action, Horror, Sci-Fi",
imDbRating: "5.8",
},
{
id: "tt6751668",
title: "Parasite",
fullTitle: "Parasite (2019)",
year: "2019",
image: "https://imdb-api.com/images/original/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_Ratio0.6737_AL_.jpg",
plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
directors: "Bong Joon Ho",
stars: "Kang-ho Song, Lee Sun-kyun, Yeo-jeong Cho",
genres: "Comedy, Drama, Thriller",
imDbRating: "8.6",
},
],
trailer: {
imDbId: "tt10048342",
title: "The Queen's Gambit",
fullTitle: "The Queen's Gambit (TV Mini-Series 2020)",
type: "TVSeries",
year: "2020",
videoId: "vi1185857817",
videoTitle: "Official Trailer",
videoDescription: "When winning takes everything, what are you left with? The Queens Gambit follows a young chess prodigys rise from an orphanage to the world stage. But genius comes with a cost. A riveting adaptation of Walter Tevis groundbreaking novel comes to Netflix on October 23rd, starring Anya Taylor-Joy.",
thumbnailUrl: "https://m.media-amazon.com/images/M/MV5BYzUzMTg4MGEtZTFmOC00NmMzLTg3NmQtZDA3ZDk4OTIwNzhlXkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg",
uploadDate: "09/24/2020 15:34:17",
link: "https://www.imdb.com/video/vi1185857817",
linkEmbed: "https://www.imdb.com/video/imdb/vi1185857817/imdb/embed",
errorMessage: "",
}
}