export default {
searchType: "Title",
expression: "green",
results: [
{
id: "tt1826684",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BMTUwODQ1NTQ5MF5BMl5BanBnXkFtZTgwMjM1NTA2MDE@._V1_Ratio0.7273_AL_.jpg",
title: "Green",
description: "(2011)",
},
{
id: "tt7060688",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BMzJjNWFhYjktNDE3NC00MWNjLWFmYWQtNGU1OTRjZGY4ODJkXkEyXkFqcGdeQXVyNjc3NTg0NzQ@._V1_Ratio0.7727_AL_.jpg",
title: "Green",
description: "(III) (2018) (Short)",
},
{
id: "tt2750524",
resultType: "Title",
image: "https://imdb-api.com/images/original/nopicture.jpg",
title: "Untitled Bounty Hunter Project",
description: "(2013) (TV Movie) aka "Green"",
},
{
id: "tt7737786",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BMzcyMzU4MDUtM2JhOC00ZDg2LTg5MGMtZjc2OGMyMjhlMGE2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.7273_AL_.jpg",
title: "Greenland",
description: "(2020)",
},
{
id: "tt2193021",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BMTI0NTMwMDgtYTMzZC00YmJhLTg4NzMtMTc1NjI4MWY4NmQ4XkEyXkFqcGdeQXVyNTY3MTYzOTA@._V1_Ratio0.7727_AL_.jpg",
title: "Arrow",
description: "(2012) (TV Series) aka "Green Arrow"",
},
{
id: "tt6966692",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BYzIzYmJlYTYtNGNiYy00N2EwLTk4ZjItMGYyZTJiOTVkM2RlXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_Ratio0.7273_AL_.jpg",
title: "Green Book",
description: "(2018)",
},
{
id: "tt9243946",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_Ratio0.7727_AL_.jpg",
title: "El Camino: A Breaking Bad Movie",
description: "(2019) aka "Greenbriar"",
},
{
id: "tt1133985",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BZjQ1YTIxNzEtMzcxNC00NTUzLThkZjktMmJlYTcyMjBhMGUyXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_Ratio0.7273_AL_.jpg",
title: "Green Lantern",
description: "(2011)",
},
{
id: "tt0120689",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_Ratio0.7273_AL_.jpg",
title: "The Green Mile",
description: "(1999)",
},
{
id: "tt9243804",
resultType: "Title",
image: "https://imdb-api.com/images/original/MV5BMjMxNTdiNWMtOWY0My00MjM4LTkwNzMtOGI0YThhN2Q4M2I4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.7273_AL_.jpg",
title: "The Green Knight",
description: "(2021)",
},
],
errorMessage: "",
}